authorize: remove admin
pomerium/pomerium pull request #1833
Opened 2021-01-28 21:54 UTC by calebdoxsey

## Summary
This PR removes the admin check in authorize as well as the configuration option.

## Checklist
- [ ] reference any related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

2021-01-28 22:33 UTC, wasaga approved these changes

2021-01-28 23:02 UTC, desimone requested changes
LGTM; just need a breaking change added to upgrade guide & update the docs?

2021-01-28 23:02 UTC, desimone commented on config/options.go
> -	Administrators []string `mapstructure:"administrators" yaml:"administrators,omitempty"`
We should add a breaking item to the UPGRADE guide / changelog and update the docs?

2021-02-01 21:56 UTC, desimone approved these changes

2021-02-01 22:22 UTC, merged