fix: use correct name for code-server
pomerium/pomerium pull request #2223
Opened 2021-05-19 17:55 UTC by jsjoeio

## Summary

Updates documentation to use the correct name for code-server

## Related issues

Fixes #2222 

## Checklist

- [ ] reference any related issues
- [x] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [ ] add appropriate tag (`improvement` / `bug` / etc)
- [ ] ready for review

2021-05-19 17:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pomerium/pomerium?pullRequest=2223) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pomerium/pomerium?pullRequest=2223) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pomerium/pomerium?pullRequest=2223) it.</sub>

2021-05-19 18:07 UTC, desimone requested changes
Thanks for the PR @jsjoeio  -- Could you also update the links?

2021-05-19 18:12 UTC, jsjoeio commented
Updated! Let me know if I missed any.

2021-05-20 00:22 UTC, desimone requested changes
One small issue. 

Also, I just saw that you are a maintainer of code-server. It has been a while since I tried this guide with the software. Have you tested it? If so, would you recommend any other general changes?

Also, let me know if we can be helpful in being part of the auth story for code. I think the assertion header + code could be a great way to pass along user identity similar to how we work with grafana.

2021-05-20 00:22 UTC, desimone commented on docs/guides/code-server.md
> -[visual studio code server]: https://github.com/cdr/code-server
I believe this needs a dash.

2021-05-20 18:20 UTC, jsjoeio commented on docs/guides/code-server.md
> -[visual studio code server]: https://github.com/cdr/code-server
Whoops! Missed that. Updated just now

2021-05-20 18:28 UTC, jsjoeio commented
> Also, I just saw that you are a maintainer of code-server. It has been a while since I tried this guide with the software. Have you tested it? 

I have not. The first time I heard about it was this week when a community member mentioned it [here](https://github.com/cdr/code-server/issues/2636#issuecomment-844109621). I can try and find some time to test it out soon though.  

> If so, would you recommend any other general changes?

Nothing specifically but let me see if @bpmct has any feedback. 

> Also, let me know if we can be helpful in being part of the auth story for code

Thanks for offering that! We really appreciate it ♥️

2021-05-20 19:34 UTC, bpmct commented
Thanks for looping me in @jsjoeio. I can also test this approach, as I know our architecture has changed a bit from when the initial guide was created. I can also record a short video on how it works and share on our YouTube :)

2021-05-20 22:06 UTC, jsjoeio commented
Updated the config and added a redirect (because I changed the file name)

2021-05-21 03:44 UTC, desimone approved these changes
LGTM! Thanks @jsjoeio !

2021-05-21 03:44 UTC, merged