envoyconfig: fallback to global custom ca when no policy ca is defined
pomerium/pomerium pull request #2235
Opened 2021-05-24 15:33 UTC by calebdoxsey

## Summary
Fallback to the custom ca defined in the global options when no policy ca is defined. 

There's a non-trivial chance this may break existing users, since previously we only validated internal connections between pomerium services using this certificate authority, and now we will be validating all upstream services.

## Related issues
Fixes https://github.com/pomerium/internal/issues/417

## Checklist
- [x] reference any related issues
- [ ] updated docs
- [x] updated unit tests
- [x] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

2021-05-25 15:14 UTC, wasaga approved these changes
The code LGTM.

- Please add an explicit warning log entry during that route X will have global CA applied, so that users who run into upstream unavailability could figure out why without reading docs.

2021-05-25 15:24 UTC, travisgroth requested changes
Discussed with @desimone yesterday and augmenting the system cert pool rather than replacing it makes the most sense for this option.  That's how the internal golang grpc and http clients currently function.  

Doing something like https://github.com/pomerium/pomerium/blob/a1061c5c03705aa69333540fad2792acb916b53c/pkg/cryptutil/tls.go#L17 for building the envoy upstream tls context would be the desired behavior.

2021-05-25 15:49 UTC, calebdoxsey commented
We can't use that function. It has no way of serializing back to PEM.

I guess I'll concatenate the PEM files, though I don't know enough about the format to know if that actually works or not.

2021-05-28 14:22 UTC, travisgroth approved these changes

2021-05-28 15:36 UTC, merged