authorize: preserve original context
pomerium/pomerium pull request #2247
Opened 2021-05-29 18:27 UTC by wasaga

## Summary

If an incoming request contains X-Pomerium-Jwt-Assertion and does not contain X-Pomerium-Jwt-Assertion-For, copy X-Pomerium-Jwt-Assertion into X-Pomerium-Jwt-Assertion-For when proxying to the upstream.

## Related issues

Implements https://github.com/pomerium/internal/issues/410

## Checklist

- [x] reference any related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

2021-05-31 18:15 UTC, desimone requested changes

2021-05-31 19:47 UTC, wasaga commented on authorize/evaluator/evaluator.go
> +// note that src keys are expected to be http.CanonicalHeaderKey
but Go maps are not case insensitive. what arrives into this func is already converted to canonical key form though; it's just a note to future reader.

2021-05-31 20:05 UTC, desimone approved these changes

2021-06-01 12:11 UTC, calebdoxsey approved these changes

2021-06-01 15:10 UTC, merged