redirect docs root  to the marketing site
pomerium/pomerium pull request #2441
Opened 2021-08-05 21:45 UTC by alexfornuto

## Summary

This brings users back to the marketing site when they click on the Pomerium logo.

## Checklist

- [ ] reference any related issues
- [X] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [ ] add appropriate tag (`improvement` / `bug` / etc)
- [X] ready for review

2021-08-05 21:47 UTC, desimone requested changes

2021-08-05 21:47 UTC, desimone commented on docs/readme.md
> +<Redirect to="https://pomerium.com" />
```suggestion
<Redirect to="https://www.pomerium.com" />
```

2021-08-05 22:02 UTC, desimone requested changes
I think this will break our current configuration in subtle ways with the CDN setup, and the auto-redirect off the SPA vuepress page.

2021-08-05 22:07 UTC, alexfornuto commented
The preview environment seems to work: https://deploy-preview-2441--pomerium-docs.netlify.app/docs/

2021-08-05 22:17 UTC, desimone approved these changes

2021-08-05 23:36 UTC, desimone approved these changes

2021-08-06 00:08 UTC, desimone approved these changes

2021-08-06 00:08 UTC, merged