Document tracing sample rate in console
pomerium/pomerium pull request #2461
Opened 2021-08-09 20:36 UTC by alexfornuto

## Summary

Documents Tracing Sample Rate notation in the Console, which is different from the OSS key.

## Related issues

Closes https://github.com/pomerium/pomerium-console/issues/1159

## Checklist

- [ ] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [ ] add appropriate tag (`improvement` / `bug` / etc)
- [ ] ready for review

2021-08-09 21:02 UTC, travisgroth requested changes

2021-08-09 21:02 UTC, travisgroth commented on docs/enterprise/console-settings.yaml
> +                  Percentage of requests to sample in decimal notation. Default is .01%.
```suggestion
                  Percentage of requests to sample. Default is .01%.
```

2021-08-10 00:17 UTC, alexfornuto commented on docs/enterprise/console-settings.yaml
> +                  Percentage of requests to sample in decimal notation. Default is .01%.
![doh](https://user-images.githubusercontent.com/2349184/128789900-44717b51-0845-4f90-94a4-f8a38a154e88.gif)

2021-08-10 00:26 UTC, travisgroth approved these changes

2021-08-10 01:19 UTC, merged