config: remove signature_key_algorithm
pomerium/pomerium pull request #2557
Opened 2021-09-01 18:04 UTC by calebdoxsey

## Summary
Remove `signing_key_algorithm` and infer it from `signing_key`.

## Related issues
Fixes https://github.com/pomerium/internal/issues/521

## Checklist
- [x] reference any related issues
- [x] updated docs
- [x] updated unit tests
- [x] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

2021-09-01 19:07 UTC, desimone requested changes
LGTM. Only suggestion would be to directly test the exported `SignatureAlgorithmForKey` function.

2021-09-01 19:07 UTC, desimone commented on pkg/cryptutil/jose.go
> +func SignatureAlgorithmForKey(key interface{}) (jose.SignatureAlgorithm, error) {
Could we add a few unit tests that explicitly test this function for both private and public keys for both algo types?

2021-09-02 03:21 UTC, alexfornuto commented on docs/docs/upgrading.md
> +The `signing_key_algorithm` option has been removed and will now be inferred from `signing_key`.
Is this being backported to 15.0?

2021-09-02 15:55 UTC, calebdoxsey commented on docs/docs/upgrading.md
> +The `signing_key_algorithm` option has been removed and will now be inferred from `signing_key`.
No it should not be backported.

2021-09-02 16:09 UTC, alexfornuto approved these changes

2021-09-02 17:34 UTC, desimone approved these changes

2021-09-02 17:36 UTC, merged