cleanup headers
pomerium/pomerium pull request #5408
Opened 2024-12-26 22:17 UTC by calebdoxsey

## Summary
Remove `HeadersRequest` and just use `Request`. This separation used to make sense when we evaluated headers with rego, but doesn't make much sense anymore.

## Related issues
 

## User Explanation

## Checklist

- [ ] reference any related issues
- [x] updated unit tests
- [x] add appropriate label (`enhancement`, `bug`, `breaking`, `dependencies`, `ci`)
- [x] ready for review

2024-12-27 17:10 UTC, kralicky requested changes

2024-12-27 17:10 UTC, kralicky commented on authorize/evaluator/headers_evaluator_evaluation.go
> +	}
this looks like it might have been incorrect in the original code, should it be building a list of audiences?

2025-01-02 22:15 UTC, calebdoxsey commented on authorize/evaluator/headers_evaluator_evaluation.go
> +	}
I don't think it supports an array. It's a query string parameter sent to the GCP identity service.

2025-01-02 22:16 UTC, calebdoxsey commented on authorize/evaluator/headers_evaluator_evaluation.go
> +		return ""
I updated it to return an error.

2025-01-03 00:03 UTC, kralicky commented on authorize/evaluator/headers_evaluator_evaluation.go
> +	}
Oh didn't notice this was specifically for google cloud.

2025-01-03 00:03 UTC, kralicky approved these changes

2025-01-06 16:52 UTC, merged